### ISSUE TITLE
no support for next_page_token

### ISSUE THREAD

**Issue by seiyria** [srirangan/googleplaces.js#21]
this is pretty important to get maximum results from google places.

**Comment by Srirangan** [comment]
i've not looked into this yet, but does `next_page_token` required special handling? can it not be part of the regular params?

**Comment by seiyria** [comment]
You sometimes get a next page token from the first query if there are more results, but if I take it and pass it back into the google places call it's ignored.

**Comment by SashaDesigN** [comment]
Yes I have the same issue, can't paginate, I pass this props:
```
{ location: '48.8582686,2.3371635',
  type: 'restaurant',
  key: 'mykey',
  radius: 5000,
  page_token: 'mynexttoken' }
```
Maybe I do something wrong?

**Comment by inameandy** [comment]
In regards to SashaDesigN's question. The correct parameter name should be "pagetoken" and not "page_token".
